// GENERATED by scripts/update-obsidian-mobile.js — do not edit.
//
// Single source of truth for the currently-vendored Obsidian mobile version
// string. See docs/plans/electron-shim-foundation.md §3.0 for why every
// reader of the version string must share this one value.
//
// Regenerated by `node scripts/update-obsidian-mobile.js [--version X.Y.Z]`
// every time the vendored bundle is updated — committed so a fresh checkout
// that never ran the script still has a valid value.
window.__owObsidianVersion = '1.12.7';
